---
deployment:
  tasks:
    # مسیر ریپو
    - export REPOPATH=/home/isbtoevq/repo/

    # مسیر سایت اصلی
    - export DEPLOYPATH=/home/isbtoevq/public_html/

    # ساخت مسیر wp-content در صورت نبودن
    - mkdir -p $DEPLOYPATH/wp-content/

    # سینک پلاگین‌ها
    - /bin/rsync -av $REPOPATH/wp-content/plugins/ $DEPLOYPATH/wp-content/plugins/

    # سینک قالب‌ها
    - /bin/rsync -av $REPOPATH/wp-content/themes/ $DEPLOYPATH/wp-content/themes/

    # سینک mu-plugins
    - /bin/rsync -av $REPOPATH/wp-content/mu-plugins/ $DEPLOYPATH/wp-content/mu-plugins/

    # سینک سایر محتوای wp-content، به جز uploads
    - /bin/rsync -av --exclude="uploads/" --exclude=".git/" $REPOPATH/wp-content/ $DEPLOYPATH/wp-content/
