---
deployment:
  tasks:
    - export REPOPATH=/home/isbtoevq/repo/
    - export DEPLOYPATH=/home/isbtoevq/public_html/

    # قالب پروژه
    - /bin/cp -R $REPOPATH/wp-content/themes/digikala-theme $DEPLOYPATH/wp-content/themes/

    # پلاگین‌های پروژه
    - /bin/cp -R $REPOPATH/wp-content/plugins $DEPLOYPATH/wp-content/
